!=======================================================================
! Generated by  : PSCAD v4.6.2.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    EMTDC_ITFP    ! Interpolated Thyristor Firing Pulses
!     SUBR    EMTDC_XONDLAY  ! 'Delay Function with Interpolation'
!     SUBR    Valve_LTTDyn  ! 
!     SUBR    Valve_ETTDyn  ! 
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5, IT_6
      INTEGER  FP_I6_scr, IT_7, IT_8, IT_9
      INTEGER  FP_I4_scr, IT_10, IT_11, IT_12
      INTEGER  IT_13, IT_14, IT_15, FP_I5_scr
      INTEGER  IT_16, IT_17, BLK_I, IT_18
      INTEGER  FP_R2_scr, IT_19, IT_20, IT_21
      INTEGER  IT_22, IT_23, IT_24, IT_25, IT_26
      INTEGER  IT_27, FP_R1_scr, IT_28, IT_29
      INTEGER  IT_30, IT_31, IT_32, IT_33, IT_34
      INTEGER  IT_35, DBlock_I, IT_36, IT_37
      INTEGER  IT_38, IT_39, IT_40, IT_41, IT_42
      INTEGER  IT_43, IT_44, IT_45, IT_46, IT_47
      INTEGER  FP_R3_scr, IT_48, DBlock_R, BLK_R
      INTEGER  FP_R5_scr, FP_R4_scr, FP_R6_scr
      INTEGER  FP_I1_gct, FP_I1_scr, FP_I3_gct
      INTEGER  FP_I3_scr, FP_I5_gct, FP_I2_gct
      INTEGER  FP_I2_scr, FP_I4_gct, FP_I6_gct
      INTEGER  FP_R1_gct, FP_R2_gct, FP_R3_gct
      INTEGER  FP_R4_gct, FP_R5_gct, FP_R6_gct
      REAL     RT_1, Alpha_R, Alpha_I, RT_2
      REAL     Uacv_I(3), Udc_I, Udc_R, Uacv_R(3)
      REAL     RT_3(6), RT_4(6), U_R1, U_R2, U_R3
      REAL     U_R4, U_R5, U_R6, RT_5(6), RT_6(6)
      REAL     U_I1, U_I2, U_I3, U_I4, U_I5, U_I6
      REAL     RT_7(6), RT_8(6), Pac_R, Qac_R
      REAL     Idc_R, Idc_I, Qac_I, Pac_I, RT_9
      REAL     RT_10, RT_11, I_I6, Maxcut_I
      REAL     RT_12, RT_13, RT_14, I_I4, RT_15
      REAL     RT_16, RT_17, I_I2, RT_18, RT_19
      REAL     RT_20, I_I5, RT_21, RT_22, RT_23
      REAL     I_I3, RT_24, RT_25, RT_26, I_I1
      REAL     I_R6, Maxcut_R, RT_27, RT_28
      REAL     RT_29, I_R4, RT_30, RT_31, RT_32
      REAL     I_R2, RT_33, RT_34, RT_35, I_R5
      REAL     RT_36, RT_37, RT_38, RT_39, I_R3
      REAL     RT_40, RT_41, RT_42, RT_43, RT_44
      REAL     RT_45, RT_46, RT_47, RT_48, RT_49
      REAL     RT_50, RT_51, RT_52, RT_53, RT_54
      REAL     RT_55, RT_56(2), RT_57, RT_58(2)
      REAL     RT_59, RT_60(2), RT_61, RT_62(2)
      REAL     RT_63, RT_64(2), RT_65, RT_66(2)
      REAL     RT_67, RT_68(2), RT_69, RT_70(2)
      REAL     RT_71, RT_72(2), RT_73, RT_74(2)
      REAL     RT_75, RT_76(2), RT_77, RT_78(2)
      REAL     RT_79, RT_80, I_R1, RT_81, RT_82
      REAL     RT_83, RT_84, RT_85, RT_86, RT_87
      REAL     RT_88, RT_89, theta_I(6), RT_90
      REAL     RT_91, RT_92, theta_R(6), EMOV_V
      REAL     RT_93(6), Uac_I(3), Uac_R(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD2_1(2), RVD1_2, RVD1_3
      REAL     RVD2_2(2), RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ICX, IPGB                           ! Control/Monitoring
      INTEGER ISUBS, SS(2), IBRCH(2), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 76
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 201
      IPGB      = NPGB
      NPGB      = NPGB + 63
      ICX       = NCX
      NCX       = NCX + 6
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 2

      DO IT_0 = 1,2
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 32

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 32
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      Alpha_R  = STOF(ISTOF + 2)
      Alpha_I  = STOF(ISTOF + 3)
      RT_2     = STOF(ISTOF + 4)
      Udc_I    = STOF(ISTOF + 8)
      Udc_R    = STOF(ISTOF + 9)
      U_R1     = STOF(ISTOF + 25)
      U_R2     = STOF(ISTOF + 26)
      U_R3     = STOF(ISTOF + 27)
      U_R4     = STOF(ISTOF + 28)
      U_R5     = STOF(ISTOF + 29)
      U_R6     = STOF(ISTOF + 30)
      U_I1     = STOF(ISTOF + 43)
      U_I2     = STOF(ISTOF + 44)
      U_I3     = STOF(ISTOF + 45)
      U_I4     = STOF(ISTOF + 46)
      U_I5     = STOF(ISTOF + 47)
      U_I6     = STOF(ISTOF + 48)
      Pac_R    = STOF(ISTOF + 61)
      Qac_R    = STOF(ISTOF + 62)
      Idc_R    = STOF(ISTOF + 63)
      Idc_I    = STOF(ISTOF + 64)
      Qac_I    = STOF(ISTOF + 65)
      Pac_I    = STOF(ISTOF + 66)
      IT_1     = STOI(ISTOI + 1)
      RT_9     = STOF(ISTOF + 67)
      IT_2     = STOI(ISTOI + 2)
      RT_10    = STOF(ISTOF + 68)
      IT_3     = STOI(ISTOI + 3)
      RT_11    = STOF(ISTOF + 69)
      I_I6     = STOF(ISTOF + 70)
      Maxcut_I = STOF(ISTOF + 71)
      IT_4     = STOI(ISTOI + 4)
      RT_12    = STOF(ISTOF + 72)
      IT_5     = STOI(ISTOI + 5)
      RT_13    = STOF(ISTOF + 73)
      IT_6     = STOI(ISTOI + 6)
      RT_14    = STOF(ISTOF + 74)
      FP_I6_scr = STOI(ISTOI + 7)
      I_I4     = STOF(ISTOF + 75)
      IT_7     = STOI(ISTOI + 8)
      RT_15    = STOF(ISTOF + 76)
      IT_8     = STOI(ISTOI + 9)
      RT_16    = STOF(ISTOF + 77)
      IT_9     = STOI(ISTOI + 10)
      RT_17    = STOF(ISTOF + 78)
      FP_I4_scr = STOI(ISTOI + 11)
      I_I2     = STOF(ISTOF + 79)
      IT_10    = STOI(ISTOI + 12)
      RT_18    = STOF(ISTOF + 80)
      IT_11    = STOI(ISTOI + 13)
      RT_19    = STOF(ISTOF + 81)
      IT_12    = STOI(ISTOI + 14)
      RT_20    = STOF(ISTOF + 82)
      I_I5     = STOF(ISTOF + 83)
      IT_13    = STOI(ISTOI + 15)
      RT_21    = STOF(ISTOF + 84)
      IT_14    = STOI(ISTOI + 16)
      RT_22    = STOF(ISTOF + 85)
      IT_15    = STOI(ISTOI + 17)
      RT_23    = STOF(ISTOF + 86)
      FP_I5_scr = STOI(ISTOI + 18)
      I_I3     = STOF(ISTOF + 87)
      IT_16    = STOI(ISTOI + 19)
      RT_24    = STOF(ISTOF + 88)
      IT_17    = STOI(ISTOI + 20)
      BLK_I    = STOI(ISTOI + 21)
      RT_25    = STOF(ISTOF + 89)
      IT_18    = STOI(ISTOI + 22)
      RT_26    = STOF(ISTOF + 90)
      I_I1     = STOF(ISTOF + 91)
      I_R6     = STOF(ISTOF + 92)
      Maxcut_R = STOF(ISTOF + 93)
      RT_27    = STOF(ISTOF + 94)
      FP_R2_scr = STOI(ISTOI + 23)
      IT_19    = STOI(ISTOI + 24)
      RT_28    = STOF(ISTOF + 95)
      RT_29    = STOF(ISTOF + 96)
      IT_20    = STOI(ISTOI + 25)
      IT_21    = STOI(ISTOI + 26)
      I_R4     = STOF(ISTOF + 97)
      RT_30    = STOF(ISTOF + 98)
      IT_22    = STOI(ISTOI + 27)
      RT_31    = STOF(ISTOF + 99)
      RT_32    = STOF(ISTOF + 100)
      IT_23    = STOI(ISTOI + 28)
      IT_24    = STOI(ISTOI + 29)
      I_R2     = STOF(ISTOF + 101)
      RT_33    = STOF(ISTOF + 102)
      IT_25    = STOI(ISTOI + 30)
      RT_34    = STOF(ISTOF + 103)
      RT_35    = STOF(ISTOF + 104)
      IT_26    = STOI(ISTOI + 31)
      IT_27    = STOI(ISTOI + 32)
      I_R5     = STOF(ISTOF + 105)
      RT_36    = STOF(ISTOF + 106)
      FP_R1_scr = STOI(ISTOI + 33)
      IT_28    = STOI(ISTOI + 34)
      RT_37    = STOF(ISTOF + 107)
      RT_38    = STOF(ISTOF + 108)
      IT_29    = STOI(ISTOI + 35)
      IT_30    = STOI(ISTOI + 36)
      RT_39    = STOF(ISTOF + 109)
      IT_31    = STOI(ISTOI + 37)
      I_R3     = STOF(ISTOF + 110)
      RT_40    = STOF(ISTOF + 111)
      RT_41    = STOF(ISTOF + 112)
      IT_32    = STOI(ISTOI + 38)
      IT_33    = STOI(ISTOI + 39)
      IT_34    = STOI(ISTOI + 40)
      RT_42    = STOF(ISTOF + 113)
      IT_35    = STOI(ISTOI + 41)
      DBlock_I = STOI(ISTOI + 42)
      RT_43    = STOF(ISTOF + 114)
      IT_36    = STOI(ISTOI + 43)
      IT_37    = STOI(ISTOI + 44)
      RT_44    = STOF(ISTOF + 115)
      IT_38    = STOI(ISTOI + 45)
      RT_45    = STOF(ISTOF + 116)
      IT_39    = STOI(ISTOI + 46)
      RT_46    = STOF(ISTOF + 117)
      IT_40    = STOI(ISTOI + 47)
      RT_47    = STOF(ISTOF + 118)
      IT_41    = STOI(ISTOI + 48)
      RT_48    = STOF(ISTOF + 119)
      IT_42    = STOI(ISTOI + 49)
      RT_49    = STOF(ISTOF + 120)
      IT_43    = STOI(ISTOI + 50)
      RT_50    = STOF(ISTOF + 121)
      IT_44    = STOI(ISTOI + 51)
      RT_51    = STOF(ISTOF + 122)
      IT_45    = STOI(ISTOI + 52)
      RT_52    = STOF(ISTOF + 123)
      IT_46    = STOI(ISTOI + 53)
      RT_53    = STOF(ISTOF + 124)
      IT_47    = STOI(ISTOI + 54)
      RT_54    = STOF(ISTOF + 125)
      RT_55    = STOF(ISTOF + 126)
      RT_57    = STOF(ISTOF + 129)
      RT_59    = STOF(ISTOF + 132)
      RT_61    = STOF(ISTOF + 135)
      RT_63    = STOF(ISTOF + 138)
      RT_65    = STOF(ISTOF + 141)
      RT_67    = STOF(ISTOF + 144)
      RT_69    = STOF(ISTOF + 147)
      RT_71    = STOF(ISTOF + 150)
      RT_73    = STOF(ISTOF + 153)
      RT_75    = STOF(ISTOF + 156)
      RT_77    = STOF(ISTOF + 159)
      RT_79    = STOF(ISTOF + 162)
      RT_80    = STOF(ISTOF + 163)
      FP_R3_scr = STOI(ISTOI + 55)
      IT_48    = STOI(ISTOI + 56)
      I_R1     = STOF(ISTOF + 164)
      DBlock_R = STOI(ISTOI + 57)
      BLK_R    = STOI(ISTOI + 58)
      RT_81    = STOF(ISTOF + 165)
      RT_82    = STOF(ISTOF + 166)
      RT_83    = STOF(ISTOF + 167)
      RT_84    = STOF(ISTOF + 168)
      RT_85    = STOF(ISTOF + 169)
      RT_86    = STOF(ISTOF + 170)
      RT_87    = STOF(ISTOF + 171)
      RT_88    = STOF(ISTOF + 172)
      RT_89    = STOF(ISTOF + 173)
      RT_90    = STOF(ISTOF + 180)
      RT_91    = STOF(ISTOF + 181)
      RT_92    = STOF(ISTOF + 182)
      FP_R5_scr = STOI(ISTOI + 59)
      FP_R4_scr = STOI(ISTOI + 60)
      FP_R6_scr = STOI(ISTOI + 61)
      FP_I1_gct = STOI(ISTOI + 62)
      FP_I1_scr = STOI(ISTOI + 63)
      FP_I3_gct = STOI(ISTOI + 64)
      FP_I3_scr = STOI(ISTOI + 65)
      FP_I5_gct = STOI(ISTOI + 66)
      FP_I2_gct = STOI(ISTOI + 67)
      FP_I2_scr = STOI(ISTOI + 68)
      FP_I4_gct = STOI(ISTOI + 69)
      FP_I6_gct = STOI(ISTOI + 70)
      EMOV_V   = STOF(ISTOF + 189)
      FP_R1_gct = STOI(ISTOI + 71)
      FP_R2_gct = STOI(ISTOI + 72)
      FP_R3_gct = STOI(ISTOI + 73)
      FP_R4_gct = STOI(ISTOI + 74)
      FP_R5_gct = STOI(ISTOI + 75)
      FP_R6_gct = STOI(ISTOI + 76)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_56(IT_0) = STOF(ISTOF + 126 + IT_0)
         RT_58(IT_0) = STOF(ISTOF + 129 + IT_0)
         RT_60(IT_0) = STOF(ISTOF + 132 + IT_0)
         RT_62(IT_0) = STOF(ISTOF + 135 + IT_0)
         RT_64(IT_0) = STOF(ISTOF + 138 + IT_0)
         RT_66(IT_0) = STOF(ISTOF + 141 + IT_0)
         RT_68(IT_0) = STOF(ISTOF + 144 + IT_0)
         RT_70(IT_0) = STOF(ISTOF + 147 + IT_0)
         RT_72(IT_0) = STOF(ISTOF + 150 + IT_0)
         RT_74(IT_0) = STOF(ISTOF + 153 + IT_0)
         RT_76(IT_0) = STOF(ISTOF + 156 + IT_0)
         RT_78(IT_0) = STOF(ISTOF + 159 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Uacv_I(IT_0) = STOF(ISTOF + 4 + IT_0)
         Uacv_R(IT_0) = STOF(ISTOF + 9 + IT_0)
         Uac_I(IT_0) = STOF(ISTOF + 195 + IT_0)
         Uac_R(IT_0) = STOF(ISTOF + 198 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         RT_3(IT_0) = STOF(ISTOF + 12 + IT_0)
         RT_4(IT_0) = STOF(ISTOF + 18 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_6(IT_0) = STOF(ISTOF + 36 + IT_0)
         RT_7(IT_0) = STOF(ISTOF + 48 + IT_0)
         RT_8(IT_0) = STOF(ISTOF + 54 + IT_0)
         theta_I(IT_0) = STOF(ISTOF + 173 + IT_0)
         theta_R(IT_0) = STOF(ISTOF + 182 + IT_0)
         RT_93(IT_0) = STOF(ISTOF + 189 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 40:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1952974997)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+29),1)

! 550:[var_switch] Two State Switch 'DBlock_R'
      RT_1 = CX(CXMAP(ICX+1))

! 570:[time-sig] Output of Simulation Time 
      RT_86 = TIME

! 580:[var] Variable Input Slider 'Alpha_R'
      Alpha_R = CX(CXMAP(ICX+2))

! 590:[var] Variable Input Slider 'Maxcut_R'
      Maxcut_R = CX(CXMAP(ICX+3))

! 610:[const] Real Constant 

      RT_85 = 0.05

! 630:[var_switch] Two State Switch 'DBlock_I'
      RT_2 = CX(CXMAP(ICX+4))

! 650:[time-sig] Output of Simulation Time 
      RT_81 = TIME

! 670:[var] Variable Input Slider 'Alpha_I'
      Alpha_I = CX(CXMAP(ICX+5))

! 680:[var] Variable Input Slider 'Maxcut_I'
      Maxcut_I = CX(CXMAP(ICX+6))

! 690:[const] Real Constant 

      RT_82 = 0.05

! 700:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R1,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_42 = RVD2_1(1)

! 710:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R2,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_33 = RVD2_1(1)

! 720:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I1,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_24 = RVD2_1(1)

! 730:[const] Real Constant 

      RT_79 = 0.004

! 740:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I2,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_15 = RVD2_1(1)

! 750:[const] Real Constant 

      RT_34 = 0.004

! 760:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R3,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_39 = RVD2_1(1)

! 770:[const] Real Constant 

      RT_26 = 0.004

! 780:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R4,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_30 = RVD2_1(1)

! 790:[const] Real Constant 

      RT_17 = 0.004

! 800:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I3,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_21 = RVD2_1(1)

! 810:[const] Real Constant 

      RT_40 = 0.004

! 820:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I4,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_12 = RVD2_1(1)

! 830:[const] Real Constant 

      RT_31 = 0.004

! 840:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R5,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_36 = RVD2_1(1)

! 850:[const] Real Constant 

      RT_23 = 0.004

! 860:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R6,Maxcut_R,0.0,0.0,1.0,RVD2_1)
      RT_27 = RVD2_1(1)

! 870:[const] Real Constant 

      RT_14 = 0.004

! 880:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I5,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_18 = RVD2_1(1)

! 890:[const] Real Constant 

      RT_37 = 0.004

! 900:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I6,Maxcut_I,0.0,0.0,1.0,RVD2_1)
      RT_9 = RVD2_1(1)

! 910:[const] Real Constant 

      RT_28 = 0.004

! 920:[const] Real Constant 

      RT_20 = 0.004

! 930:[const] Real Constant 

      RT_11 = 0.004

! 950:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_86,RT_85,1.0,0.0,0.0,RVD2_1)
      RT_84 = RVD2_1(1)

! 980:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_81,RT_82,1.0,0.0,0.0,RVD2_1)
      RT_83 = RVD2_1(1)

! 1100:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R1,RT_79,0.0,0.0,1.0,RVD2_1)
      RT_80 = RVD2_1(1)

! 1110:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R2,RT_34,0.0,0.0,1.0,RVD2_1)
      RT_35 = RVD2_1(1)

! 1120:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I1,RT_26,0.0,0.0,1.0,RVD2_1)
      RT_25 = RVD2_1(1)

! 1130:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I2,RT_17,0.0,0.0,1.0,RVD2_1)
      RT_16 = RVD2_1(1)

! 1140:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R3,RT_40,0.0,0.0,1.0,RVD2_1)
      RT_41 = RVD2_1(1)

! 1150:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R4,RT_31,0.0,0.0,1.0,RVD2_1)
      RT_32 = RVD2_1(1)

! 1160:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I3,RT_23,0.0,0.0,1.0,RVD2_1)
      RT_22 = RVD2_1(1)

! 1170:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I4,RT_14,0.0,0.0,1.0,RVD2_1)
      RT_13 = RVD2_1(1)

! 1180:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R5,RT_37,0.0,0.0,1.0,RVD2_1)
      RT_38 = RVD2_1(1)

! 1190:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_R6,RT_28,0.0,0.0,1.0,RVD2_1)
      RT_29 = RVD2_1(1)

! 1200:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I5,RT_20,0.0,0.0,1.0,RVD2_1)
      RT_19 = RVD2_1(1)

! 1210:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,I_I6,RT_11,0.0,0.0,1.0,RVD2_1)
      RT_10 = RVD2_1(1)

! 1220:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_1) .NE. 0) .AND. (NINT(RT_84) .NE. 0) ) THEN
        DBlock_R = 1
      ELSE
        DBlock_R = 0
      ENDIF

! 1230:[inv] Interpolated Logic Inverter 
      IF (DBlock_R .NE. 0) THEN
         BLK_R = 0
      ELSE
         BLK_R = 1
      ENDIF

! 1240:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_2) .NE. 0) .AND. (NINT(RT_83) .NE. 0) ) THEN
        DBlock_I = 1
      ELSE
        DBlock_I = 0
      ENDIF

! 1250:[inv] Interpolated Logic Inverter 
      IF (DBlock_I .NE. 0) THEN
         BLK_I = 0
      ELSE
         BLK_I = 1
      ENDIF

! 1260:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_78(1) : OUTPUT PULSE
!    RT_78(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_77,Alpha_R,RT_78)
!

! 1270:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_76(1) : OUTPUT PULSE
!    RT_76(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_75,Alpha_R,RT_76)
!

! 1280:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_74(1) : OUTPUT PULSE
!    RT_74(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_73,Alpha_R,RT_74)
!

! 1290:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_72(1) : OUTPUT PULSE
!    RT_72(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_71,Alpha_R,RT_72)
!

! 1300:[datatap] Scalar/Array Tap 
      RT_49 = RT_78(1)

! 1310:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_70(1) : OUTPUT PULSE
!    RT_70(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_69,Alpha_R,RT_70)
!

! 1320:[datatap] Scalar/Array Tap 
      RT_50 = RT_76(1)

! 1330:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_68(1) : OUTPUT PULSE
!    RT_68(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_R,0.004,RVD1_1,RVD1_2,RT_67,Alpha_R,RT_68)
!

! 1340:[datatap] Scalar/Array Tap 
      RT_51 = RT_74(1)

! 1350:[unity] Type conversion block 
! real -> nearest integer
      IT_42 = NINT(RT_49)

! 1360:[datatap] Scalar/Array Tap 
      RT_52 = RT_72(1)

! 1370:[unity] Type conversion block 
! real -> nearest integer
      IT_43 = NINT(RT_50)

! 1380:[datatap] Scalar/Array Tap 
      RT_53 = RT_70(1)

! 1390:[unity] Type conversion block 
! real -> nearest integer
      IT_44 = NINT(RT_51)

! 1400:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_42 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R1_scr = 1
      ELSE
        FP_R1_scr = 0
      ENDIF

! 1410:[datatap] Scalar/Array Tap 
      RT_54 = RT_68(1)

! 1420:[unity] Type conversion block 
! real -> nearest integer
      IT_45 = NINT(RT_52)

! 1430:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_56(1) : OUTPUT PULSE
!    RT_56(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_55,Alpha_I,RT_56)
!

! 1440:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_43 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R2_scr = 1
      ELSE
        FP_R2_scr = 0
      ENDIF

! 1450:[unity] Type conversion block 
! real -> nearest integer
      IT_46 = NINT(RT_53)

! 1460:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_58(1) : OUTPUT PULSE
!    RT_58(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_57,Alpha_I,RT_58)
!

! 1470:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_44 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R3_scr = 1
      ELSE
        FP_R3_scr = 0
      ENDIF

! 1480:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_60(1) : OUTPUT PULSE
!    RT_60(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_59,Alpha_I,RT_60)
!

! 1490:[unity] Type conversion block 
! real -> nearest integer
      IT_47 = NINT(RT_54)

! 1500:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_45 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R4_scr = 1
      ELSE
        FP_R4_scr = 0
      ENDIF

! 1510:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_62(1) : OUTPUT PULSE
!    RT_62(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_61,Alpha_I,RT_62)
!

! 1520:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_46 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R5_scr = 1
      ELSE
        FP_R5_scr = 0
      ENDIF

! 1530:[datatap] Scalar/Array Tap 
      RT_43 = RT_56(1)

! 1540:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_64(1) : OUTPUT PULSE
!    RT_64(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_63,Alpha_I,RT_64)
!

! 1550:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_47 .NE. 0) .AND. (BLK_R .EQ. 0) ) THEN
        FP_R6_scr = 1
      ELSE
        FP_R6_scr = 0
      ENDIF

! 1560:[datatap] Scalar/Array Tap 
      RT_44 = RT_58(1)

! 1570:[fp_int] Interpolated Firing Pulses 
      RVD1_1 = 360.0
      RVD1_2 = 0.0
!
!  TO INTERPOLATE FIRING PULSES
!    RT_66(1) : OUTPUT PULSE
!    RT_66(2) : DT FOR INTERPOLATION
      CALL EMTDC_ITFP(DBlock_I,0.004,RVD1_1,RVD1_2,RT_65,Alpha_I,RT_66)
!

! 1580:[datatap] Scalar/Array Tap 
      RT_45 = RT_60(1)

! 1590:[unity] Type conversion block 
! real -> nearest integer
      IT_36 = NINT(RT_43)

! 1600:[datatap] Scalar/Array Tap 
      RT_46 = RT_62(1)

! 1610:[unity] Type conversion block 
! real -> nearest integer
      IT_37 = NINT(RT_44)

! 1620:[datatap] Scalar/Array Tap 
      RT_47 = RT_64(1)

! 1630:[unity] Type conversion block 
! real -> nearest integer
      IT_38 = NINT(RT_45)

! 1640:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_36 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I1_scr = 1
      ELSE
        FP_I1_scr = 0
      ENDIF

! 1650:[datatap] Scalar/Array Tap 
      RT_48 = RT_66(1)

! 1660:[unity] Type conversion block 
! real -> nearest integer
      IT_39 = NINT(RT_46)

! 1670:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_37 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I2_scr = 1
      ELSE
        FP_I2_scr = 0
      ENDIF

! 1680:[unity] Type conversion block 
! real -> nearest integer
      IT_40 = NINT(RT_47)

! 1690:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_38 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I3_scr = 1
      ELSE
        FP_I3_scr = 0
      ENDIF

! 1700:[unity] Type conversion block 
! real -> nearest integer
      IT_41 = NINT(RT_48)

! 1710:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_39 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I4_scr = 1
      ELSE
        FP_I4_scr = 0
      ENDIF

! 1720:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_40 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I5_scr = 1
      ELSE
        FP_I5_scr = 0
      ENDIF

! 1730:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_41 .NE. 0) .AND. (BLK_I .EQ. 0) ) THEN
        FP_I6_scr = 1
      ELSE
        FP_I6_scr = 0
      ENDIF

! 1740:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R3_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_48 = NINT(RVD2_2(1))

! 1750:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R4_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_25 = NINT(RVD2_2(1))

! 1760:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R5_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_31 = NINT(RVD2_2(1))

! 1770:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R6_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_22 = NINT(RVD2_2(1))

! 1780:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R1_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_28 = NINT(RVD2_2(1))

! 1790:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_R2_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_19 = NINT(RVD2_2(1))

! 1800:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I2_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_3 = NINT(RVD2_2(1))

! 1810:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I1_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_12 = NINT(RVD2_2(1))

! 1820:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_19 .NE. 0) .OR. (NINT(RT_29) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_20 = 1
      ELSE
        IT_20 = 0
      ENDIF

! 1830:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_27) .NE. 0) .AND. (IT_20 .NE. 0) ) THEN
        IT_21 = 1
      ELSE
        IT_21 = 0
      ENDIF

! 1840:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R6_gct=0
      ELSE
        IF(FP_R6_scr.EQ.1)THEN
          FP_R6_gct=1
        ELSE
          IF(IT_21.EQ.1)THEN
            FP_R6_gct=0
          ENDIF
        ENDIF
      ENDIF

! 1850:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_28 .NE. 0) .OR. (NINT(RT_38) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_29 = 1
      ELSE
        IT_29 = 0
      ENDIF

! 1860:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_36) .NE. 0) .AND. (IT_29 .NE. 0) ) THEN
        IT_30 = 1
      ELSE
        IT_30 = 0
      ENDIF

! 1870:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R5_gct=0
      ELSE
        IF(FP_R5_scr.EQ.1)THEN
          FP_R5_gct=1
        ELSE
          IF(IT_30.EQ.1)THEN
            FP_R5_gct=0
          ENDIF
        ENDIF
      ENDIF

! 1880:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I6_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_6 = NINT(RVD2_2(1))

! 1890:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I5_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_15 = NINT(RVD2_2(1))

! 1900:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_22 .NE. 0) .OR. (NINT(RT_32) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_23 = 1
      ELSE
        IT_23 = 0
      ENDIF

! 1910:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_30) .NE. 0) .AND. (IT_23 .NE. 0) ) THEN
        IT_24 = 1
      ELSE
        IT_24 = 0
      ENDIF

! 1920:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R4_gct=0
      ELSE
        IF(FP_R4_scr.EQ.1)THEN
          FP_R4_gct=1
        ELSE
          IF(IT_24.EQ.1)THEN
            FP_R4_gct=0
          ENDIF
        ENDIF
      ENDIF

! 1930:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_31 .NE. 0) .OR. (NINT(RT_41) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_32 = 1
      ELSE
        IT_32 = 0
      ENDIF

! 1940:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_39) .NE. 0) .AND. (IT_32 .NE. 0) ) THEN
        IT_33 = 1
      ELSE
        IT_33 = 0
      ENDIF

! 1950:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R3_gct=0
      ELSE
        IF(FP_R3_scr.EQ.1)THEN
          FP_R3_gct=1
        ELSE
          IF(IT_33.EQ.1)THEN
            FP_R3_gct=0
          ENDIF
        ENDIF
      ENDIF

! 1960:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I4_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_9 = NINT(RVD2_2(1))

! 1970:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(FP_I3_scr)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0015,RVD2_1,RVD2_2)
      IT_18 = NINT(RVD2_2(1))

! 1980:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_25 .NE. 0) .OR. (NINT(RT_35) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_26 = 1
      ELSE
        IT_26 = 0
      ENDIF

! 1990:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_33) .NE. 0) .AND. (IT_26 .NE. 0) ) THEN
        IT_27 = 1
      ELSE
        IT_27 = 0
      ENDIF

! 2000:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R2_gct=0
      ELSE
        IF(FP_R2_scr.EQ.1)THEN
          FP_R2_gct=1
        ELSE
          IF(IT_27.EQ.1)THEN
            FP_R2_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2010:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_48 .NE. 0) .OR. (NINT(RT_80) .NE. 0) .OR. (BLK_R .NE. 0) &
     &) THEN
        IT_35 = 1
      ELSE
        IT_35 = 0
      ENDIF

! 2020:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_42) .NE. 0) .AND. (IT_35 .NE. 0) ) THEN
        IT_34 = 1
      ELSE
        IT_34 = 0
      ENDIF

! 2030:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_R1_gct=0
      ELSE
        IF(FP_R1_scr.EQ.1)THEN
          FP_R1_gct=1
        ELSE
          IF(IT_34.EQ.1)THEN
            FP_R1_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2040:[datamerge] Merges data signals into an array 
      RT_8(1) = REAL(FP_I1_scr)
      RT_8(2) = REAL(FP_I2_scr)
      RT_8(3) = REAL(FP_I3_scr)
      RT_8(4) = REAL(FP_I4_scr)
      RT_8(5) = REAL(FP_I5_scr)
      RT_8(6) = REAL(FP_I6_scr)

! 2050:[datamerge] Merges data signals into an array 
      RT_3(1) = REAL(FP_R1_scr)
      RT_3(2) = REAL(FP_R2_scr)
      RT_3(3) = REAL(FP_R3_scr)
      RT_3(4) = REAL(FP_R4_scr)
      RT_3(5) = REAL(FP_R5_scr)
      RT_3(6) = REAL(FP_R6_scr)

! 2060:[datamerge] Merges data signals into an array 
      RT_93(1) = REAL(FP_R1_gct)
      RT_93(2) = REAL(FP_R2_gct)
      RT_93(3) = REAL(FP_R3_gct)
      RT_93(4) = REAL(FP_R4_gct)
      RT_93(5) = REAL(FP_R5_gct)
      RT_93(6) = REAL(FP_R6_gct)

! 2070:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_3 .NE. 0) .OR. (NINT(RT_10) .NE. 0) .OR. (BLK_I .NE. 0) )&
     & THEN
        IT_2 = 1
      ELSE
        IT_2 = 0
      ENDIF

! 2080:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_9) .NE. 0) .AND. (IT_2 .NE. 0) ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 2090:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I6_gct=0
      ELSE
        IF(FP_I6_scr.EQ.1)THEN
          FP_I6_gct=1
        ELSE
          IF(IT_1.EQ.1)THEN
            FP_I6_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2100:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_12 .NE. 0) .OR. (NINT(RT_19) .NE. 0) .OR. (BLK_I .NE. 0) &
     &) THEN
        IT_11 = 1
      ELSE
        IT_11 = 0
      ENDIF

! 2110:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_18) .NE. 0) .AND. (IT_11 .NE. 0) ) THEN
        IT_10 = 1
      ELSE
        IT_10 = 0
      ENDIF

! 2120:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I5_gct=0
      ELSE
        IF(FP_I5_scr.EQ.1)THEN
          FP_I5_gct=1
        ELSE
          IF(IT_10.EQ.1)THEN
            FP_I5_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2130:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_6 .NE. 0) .OR. (NINT(RT_13) .NE. 0) .OR. (BLK_I .NE. 0) )&
     & THEN
        IT_5 = 1
      ELSE
        IT_5 = 0
      ENDIF

! 2140:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_12) .NE. 0) .AND. (IT_5 .NE. 0) ) THEN
        IT_4 = 1
      ELSE
        IT_4 = 0
      ENDIF

! 2150:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I4_gct=0
      ELSE
        IF(FP_I4_scr.EQ.1)THEN
          FP_I4_gct=1
        ELSE
          IF(IT_4.EQ.1)THEN
            FP_I4_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2160:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_15 .NE. 0) .OR. (NINT(RT_22) .NE. 0) .OR. (BLK_I .NE. 0) &
     &) THEN
        IT_14 = 1
      ELSE
        IT_14 = 0
      ENDIF

! 2170:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_21) .NE. 0) .AND. (IT_14 .NE. 0) ) THEN
        IT_13 = 1
      ELSE
        IT_13 = 0
      ENDIF

! 2180:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I3_gct=0
      ELSE
        IF(FP_I3_scr.EQ.1)THEN
          FP_I3_gct=1
        ELSE
          IF(IT_13.EQ.1)THEN
            FP_I3_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2190:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_9 .NE. 0) .OR. (NINT(RT_16) .NE. 0) .OR. (BLK_I .NE. 0) )&
     & THEN
        IT_8 = 1
      ELSE
        IT_8 = 0
      ENDIF

! 2200:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_15) .NE. 0) .AND. (IT_8 .NE. 0) ) THEN
        IT_7 = 1
      ELSE
        IT_7 = 0
      ENDIF

! 2210:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I2_gct=0
      ELSE
        IF(FP_I2_scr.EQ.1)THEN
          FP_I2_gct=1
        ELSE
          IF(IT_7.EQ.1)THEN
            FP_I2_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2220:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_18 .NE. 0) .OR. (NINT(RT_25) .NE. 0) .OR. (BLK_I .NE. 0) &
     &) THEN
        IT_17 = 1
      ELSE
        IT_17 = 0
      ENDIF

! 2230:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_24) .NE. 0) .AND. (IT_17 .NE. 0) ) THEN
        IT_16 = 1
      ELSE
        IT_16 = 0
      ENDIF

! 2240:[Pulse2Level]  
      IF(TIMEZERO)THEN
        FP_I1_gct=0
      ELSE
        IF(FP_I1_scr.EQ.1)THEN
          FP_I1_gct=1
        ELSE
          IF(IT_16.EQ.1)THEN
            FP_I1_gct=0
          ENDIF
        ENDIF
      ENDIF

! 2250:[pgb] Output Channel 'FP_I'

      DO IVD1_1 = 1, 6
         PGB(IPGB+45+IVD1_1-1) = RT_8(IVD1_1)
      ENDDO

! 2260:[pgb] Output Channel 'FP_R'

      DO IVD1_1 = 1, 6
         PGB(IPGB+51+IVD1_1-1) = RT_3(IVD1_1)
      ENDDO

! 2270:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I1_gct)


! 2280:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I3_gct)


! 2290:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I5_gct)


! 2300:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R2_gct)


! 2310:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R6_gct)


! 2320:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R4_gct)


! 2330:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I4_gct)


! 2340:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I6_gct)


! 2350:[Valve_LTT]  
      CALL Valve_LTTDyn(FP_I2_gct)


! 2360:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R5_gct)


! 2370:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R3_gct)


! 2380:[pgb] Output Channel 'EMOV_V'

      PGB(IPGB+57) = EMOV_V

! 2390:[Valve_ETT]  
      CALL Valve_ETTDyn(FP_R1_gct)


! 2400:[pgb] Output Channel 'FP_R_gct'

      DO IVD1_1 = 1, 6
         PGB(IPGB+58+IVD1_1-1) = RT_93(IVD1_1)
      ENDDO

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1306313763)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+29),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1128012386)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+28),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,431349669)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+27),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1050192662)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+28),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1731079995)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+27),1)

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: Ideal
!  
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = 0.0*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS(2), (IBRCH(2)+1), (IBRCH(2)+2), (IBRCH(2)+3)&
     &, RVD1_4, .TRUE., RVD1_1 , RVD1_2, RVD1_3)
!

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((IXFMR + 1),(IXFMR + 2),(IXFMR + 3), (IBRCH(2)+20),&
     & (IBRCH(2)+21), (IBRCH(2)+22), (IBRCH(2)+23), (IBRCH(2)+24), (IBRC&
     &H(2)+25),0,0,0,0,0,0,SS(2),0,1.0,0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  DC source: Type: R
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(2), (IBRCH(2)+26),RVD1_4,0,RVD1_1,RVD1_2,RVD1&
     &_3)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  DC source: Type: R
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+2),RVD1_4,0,RVD1_1,RVD1_2,RVD1_&
     &3)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,726492082)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+32),1)

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((IXFMR + 4),(IXFMR + 5),(IXFMR + 6), (IBRCH(1)+21),&
     & (IBRCH(1)+22), (IBRCH(1)+23), (IBRCH(1)+24), (IBRCH(1)+25), (IBRC&
     &H(1)+26),0,0,0,0,0,0,SS(1),0,1.0,0)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,116628703)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+31),1)

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: Ideal
!  
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = 0.0*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+3), (IBRCH(1)+4), (IBRCH(1)+5)&
     &, RVD1_4, .TRUE., RVD1_1 , RVD1_2, RVD1_3)
!

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1867419198)
      CALL ARRESTERZNO_EXE(SS(2), (IBRCH(2)+30),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,1369814601)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+32),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,845949602)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+31),1)

! 1:[arrester] Arrester 
!  Metal Oxide Gapless Surge Arrester: 
      CALL COMPONENT_ID(ICALL_NO,6965202)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+30),1)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = Alpha_R
      STOF(ISTOF + 3) = Alpha_I
      STOF(ISTOF + 4) = RT_2
      STOF(ISTOF + 8) = Udc_I
      STOF(ISTOF + 9) = Udc_R
      STOF(ISTOF + 25) = U_R1
      STOF(ISTOF + 26) = U_R2
      STOF(ISTOF + 27) = U_R3
      STOF(ISTOF + 28) = U_R4
      STOF(ISTOF + 29) = U_R5
      STOF(ISTOF + 30) = U_R6
      STOF(ISTOF + 43) = U_I1
      STOF(ISTOF + 44) = U_I2
      STOF(ISTOF + 45) = U_I3
      STOF(ISTOF + 46) = U_I4
      STOF(ISTOF + 47) = U_I5
      STOF(ISTOF + 48) = U_I6
      STOF(ISTOF + 61) = Pac_R
      STOF(ISTOF + 62) = Qac_R
      STOF(ISTOF + 63) = Idc_R
      STOF(ISTOF + 64) = Idc_I
      STOF(ISTOF + 65) = Qac_I
      STOF(ISTOF + 66) = Pac_I
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 67) = RT_9
      STOI(ISTOI + 2) = IT_2
      STOF(ISTOF + 68) = RT_10
      STOI(ISTOI + 3) = IT_3
      STOF(ISTOF + 69) = RT_11
      STOF(ISTOF + 70) = I_I6
      STOF(ISTOF + 71) = Maxcut_I
      STOI(ISTOI + 4) = IT_4
      STOF(ISTOF + 72) = RT_12
      STOI(ISTOI + 5) = IT_5
      STOF(ISTOF + 73) = RT_13
      STOI(ISTOI + 6) = IT_6
      STOF(ISTOF + 74) = RT_14
      STOI(ISTOI + 7) = FP_I6_scr
      STOF(ISTOF + 75) = I_I4
      STOI(ISTOI + 8) = IT_7
      STOF(ISTOF + 76) = RT_15
      STOI(ISTOI + 9) = IT_8
      STOF(ISTOF + 77) = RT_16
      STOI(ISTOI + 10) = IT_9
      STOF(ISTOF + 78) = RT_17
      STOI(ISTOI + 11) = FP_I4_scr
      STOF(ISTOF + 79) = I_I2
      STOI(ISTOI + 12) = IT_10
      STOF(ISTOF + 80) = RT_18
      STOI(ISTOI + 13) = IT_11
      STOF(ISTOF + 81) = RT_19
      STOI(ISTOI + 14) = IT_12
      STOF(ISTOF + 82) = RT_20
      STOF(ISTOF + 83) = I_I5
      STOI(ISTOI + 15) = IT_13
      STOF(ISTOF + 84) = RT_21
      STOI(ISTOI + 16) = IT_14
      STOF(ISTOF + 85) = RT_22
      STOI(ISTOI + 17) = IT_15
      STOF(ISTOF + 86) = RT_23
      STOI(ISTOI + 18) = FP_I5_scr
      STOF(ISTOF + 87) = I_I3
      STOI(ISTOI + 19) = IT_16
      STOF(ISTOF + 88) = RT_24
      STOI(ISTOI + 20) = IT_17
      STOI(ISTOI + 21) = BLK_I
      STOF(ISTOF + 89) = RT_25
      STOI(ISTOI + 22) = IT_18
      STOF(ISTOF + 90) = RT_26
      STOF(ISTOF + 91) = I_I1
      STOF(ISTOF + 92) = I_R6
      STOF(ISTOF + 93) = Maxcut_R
      STOF(ISTOF + 94) = RT_27
      STOI(ISTOI + 23) = FP_R2_scr
      STOI(ISTOI + 24) = IT_19
      STOF(ISTOF + 95) = RT_28
      STOF(ISTOF + 96) = RT_29
      STOI(ISTOI + 25) = IT_20
      STOI(ISTOI + 26) = IT_21
      STOF(ISTOF + 97) = I_R4
      STOF(ISTOF + 98) = RT_30
      STOI(ISTOI + 27) = IT_22
      STOF(ISTOF + 99) = RT_31
      STOF(ISTOF + 100) = RT_32
      STOI(ISTOI + 28) = IT_23
      STOI(ISTOI + 29) = IT_24
      STOF(ISTOF + 101) = I_R2
      STOF(ISTOF + 102) = RT_33
      STOI(ISTOI + 30) = IT_25
      STOF(ISTOF + 103) = RT_34
      STOF(ISTOF + 104) = RT_35
      STOI(ISTOI + 31) = IT_26
      STOI(ISTOI + 32) = IT_27
      STOF(ISTOF + 105) = I_R5
      STOF(ISTOF + 106) = RT_36
      STOI(ISTOI + 33) = FP_R1_scr
      STOI(ISTOI + 34) = IT_28
      STOF(ISTOF + 107) = RT_37
      STOF(ISTOF + 108) = RT_38
      STOI(ISTOI + 35) = IT_29
      STOI(ISTOI + 36) = IT_30
      STOF(ISTOF + 109) = RT_39
      STOI(ISTOI + 37) = IT_31
      STOF(ISTOF + 110) = I_R3
      STOF(ISTOF + 111) = RT_40
      STOF(ISTOF + 112) = RT_41
      STOI(ISTOI + 38) = IT_32
      STOI(ISTOI + 39) = IT_33
      STOI(ISTOI + 40) = IT_34
      STOF(ISTOF + 113) = RT_42
      STOI(ISTOI + 41) = IT_35
      STOI(ISTOI + 42) = DBlock_I
      STOF(ISTOF + 114) = RT_43
      STOI(ISTOI + 43) = IT_36
      STOI(ISTOI + 44) = IT_37
      STOF(ISTOF + 115) = RT_44
      STOI(ISTOI + 45) = IT_38
      STOF(ISTOF + 116) = RT_45
      STOI(ISTOI + 46) = IT_39
      STOF(ISTOF + 117) = RT_46
      STOI(ISTOI + 47) = IT_40
      STOF(ISTOF + 118) = RT_47
      STOI(ISTOI + 48) = IT_41
      STOF(ISTOF + 119) = RT_48
      STOI(ISTOI + 49) = IT_42
      STOF(ISTOF + 120) = RT_49
      STOI(ISTOI + 50) = IT_43
      STOF(ISTOF + 121) = RT_50
      STOI(ISTOI + 51) = IT_44
      STOF(ISTOF + 122) = RT_51
      STOI(ISTOI + 52) = IT_45
      STOF(ISTOF + 123) = RT_52
      STOI(ISTOI + 53) = IT_46
      STOF(ISTOF + 124) = RT_53
      STOI(ISTOI + 54) = IT_47
      STOF(ISTOF + 125) = RT_54
      STOF(ISTOF + 126) = RT_55
      STOF(ISTOF + 129) = RT_57
      STOF(ISTOF + 132) = RT_59
      STOF(ISTOF + 135) = RT_61
      STOF(ISTOF + 138) = RT_63
      STOF(ISTOF + 141) = RT_65
      STOF(ISTOF + 144) = RT_67
      STOF(ISTOF + 147) = RT_69
      STOF(ISTOF + 150) = RT_71
      STOF(ISTOF + 153) = RT_73
      STOF(ISTOF + 156) = RT_75
      STOF(ISTOF + 159) = RT_77
      STOF(ISTOF + 162) = RT_79
      STOF(ISTOF + 163) = RT_80
      STOI(ISTOI + 55) = FP_R3_scr
      STOI(ISTOI + 56) = IT_48
      STOF(ISTOF + 164) = I_R1
      STOI(ISTOI + 57) = DBlock_R
      STOI(ISTOI + 58) = BLK_R
      STOF(ISTOF + 165) = RT_81
      STOF(ISTOF + 166) = RT_82
      STOF(ISTOF + 167) = RT_83
      STOF(ISTOF + 168) = RT_84
      STOF(ISTOF + 169) = RT_85
      STOF(ISTOF + 170) = RT_86
      STOF(ISTOF + 171) = RT_87
      STOF(ISTOF + 172) = RT_88
      STOF(ISTOF + 173) = RT_89
      STOF(ISTOF + 180) = RT_90
      STOF(ISTOF + 181) = RT_91
      STOF(ISTOF + 182) = RT_92
      STOI(ISTOI + 59) = FP_R5_scr
      STOI(ISTOI + 60) = FP_R4_scr
      STOI(ISTOI + 61) = FP_R6_scr
      STOI(ISTOI + 62) = FP_I1_gct
      STOI(ISTOI + 63) = FP_I1_scr
      STOI(ISTOI + 64) = FP_I3_gct
      STOI(ISTOI + 65) = FP_I3_scr
      STOI(ISTOI + 66) = FP_I5_gct
      STOI(ISTOI + 67) = FP_I2_gct
      STOI(ISTOI + 68) = FP_I2_scr
      STOI(ISTOI + 69) = FP_I4_gct
      STOI(ISTOI + 70) = FP_I6_gct
      STOF(ISTOF + 189) = EMOV_V
      STOI(ISTOI + 71) = FP_R1_gct
      STOI(ISTOI + 72) = FP_R2_gct
      STOI(ISTOI + 73) = FP_R3_gct
      STOI(ISTOI + 74) = FP_R4_gct
      STOI(ISTOI + 75) = FP_R5_gct
      STOI(ISTOI + 76) = FP_R6_gct

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 126 + IT_0) = RT_56(IT_0)
         STOF(ISTOF + 129 + IT_0) = RT_58(IT_0)
         STOF(ISTOF + 132 + IT_0) = RT_60(IT_0)
         STOF(ISTOF + 135 + IT_0) = RT_62(IT_0)
         STOF(ISTOF + 138 + IT_0) = RT_64(IT_0)
         STOF(ISTOF + 141 + IT_0) = RT_66(IT_0)
         STOF(ISTOF + 144 + IT_0) = RT_68(IT_0)
         STOF(ISTOF + 147 + IT_0) = RT_70(IT_0)
         STOF(ISTOF + 150 + IT_0) = RT_72(IT_0)
         STOF(ISTOF + 153 + IT_0) = RT_74(IT_0)
         STOF(ISTOF + 156 + IT_0) = RT_76(IT_0)
         STOF(ISTOF + 159 + IT_0) = RT_78(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 4 + IT_0) = Uacv_I(IT_0)
         STOF(ISTOF + 9 + IT_0) = Uacv_R(IT_0)
         STOF(ISTOF + 195 + IT_0) = Uac_I(IT_0)
         STOF(ISTOF + 198 + IT_0) = Uac_R(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STOF(ISTOF + 12 + IT_0) = RT_3(IT_0)
         STOF(ISTOF + 18 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 30 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 36 + IT_0) = RT_6(IT_0)
         STOF(ISTOF + 48 + IT_0) = RT_7(IT_0)
         STOF(ISTOF + 54 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 173 + IT_0) = theta_I(IT_0)
         STOF(ISTOF + 182 + IT_0) = theta_R(IT_0)
         STOF(ISTOF + 189 + IT_0) = RT_93(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    E_VZNO50      ! Access calculated energy of arrester
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    Valve_LTTOut  ! 
!     SUBR    Valve_ETTOut  ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_3, NT_4, NT_5, NT_6
      INTEGER  NT_7, NT_8, NT_9, NT_10, NT_11
      INTEGER  NT_12, NT_13, NT_14, NT_15(3)
      INTEGER  NT_18, NT_21(3), NT_22(3), NT_23
      INTEGER  NT_24(3)

! Control Signals
      REAL     Uacv_I(3), Udc_I, Udc_R, Uacv_R(3)
      REAL     RT_4(6), U_R1, U_R2, U_R3, U_R4
      REAL     U_R5, U_R6, RT_5(6), RT_6(6), U_I1
      REAL     U_I2, U_I3, U_I4, U_I5, U_I6
      REAL     RT_7(6), Pac_R, Qac_R, Idc_R
      REAL     Idc_I, Qac_I, Pac_I, RT_11, I_I6
      REAL     RT_14, I_I4, RT_17, I_I2, RT_20
      REAL     I_I5, RT_23, I_I3, RT_26, I_I1
      REAL     I_R6, RT_28, I_R4, RT_31, I_R2
      REAL     RT_34, I_R5, RT_37, I_R3, RT_40
      REAL     RT_55, RT_57, RT_59, RT_61, RT_63
      REAL     RT_65, RT_67, RT_69, RT_71, RT_73
      REAL     RT_75, RT_77, RT_79, I_R1, RT_82
      REAL     RT_85, RT_87, RT_88, RT_89
      REAL     theta_I(6), RT_90, RT_91, RT_92
      REAL     theta_R(6), EMOV_V, Uac_I(3)
      REAL     Uac_R(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(2), IBRCH(2), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 63
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 2

      DO IT_0 = 1,2
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 32

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 32
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      Udc_I    = STOF(ISTOF + 8)
      Udc_R    = STOF(ISTOF + 9)
      U_R1     = STOF(ISTOF + 25)
      U_R2     = STOF(ISTOF + 26)
      U_R3     = STOF(ISTOF + 27)
      U_R4     = STOF(ISTOF + 28)
      U_R5     = STOF(ISTOF + 29)
      U_R6     = STOF(ISTOF + 30)
      U_I1     = STOF(ISTOF + 43)
      U_I2     = STOF(ISTOF + 44)
      U_I3     = STOF(ISTOF + 45)
      U_I4     = STOF(ISTOF + 46)
      U_I5     = STOF(ISTOF + 47)
      U_I6     = STOF(ISTOF + 48)
      Pac_R    = STOF(ISTOF + 61)
      Qac_R    = STOF(ISTOF + 62)
      Idc_R    = STOF(ISTOF + 63)
      Idc_I    = STOF(ISTOF + 64)
      Qac_I    = STOF(ISTOF + 65)
      Pac_I    = STOF(ISTOF + 66)
      RT_11    = STOF(ISTOF + 69)
      I_I6     = STOF(ISTOF + 70)
      RT_14    = STOF(ISTOF + 74)
      I_I4     = STOF(ISTOF + 75)
      RT_17    = STOF(ISTOF + 78)
      I_I2     = STOF(ISTOF + 79)
      RT_20    = STOF(ISTOF + 82)
      I_I5     = STOF(ISTOF + 83)
      RT_23    = STOF(ISTOF + 86)
      I_I3     = STOF(ISTOF + 87)
      RT_26    = STOF(ISTOF + 90)
      I_I1     = STOF(ISTOF + 91)
      I_R6     = STOF(ISTOF + 92)
      RT_28    = STOF(ISTOF + 95)
      I_R4     = STOF(ISTOF + 97)
      RT_31    = STOF(ISTOF + 99)
      I_R2     = STOF(ISTOF + 101)
      RT_34    = STOF(ISTOF + 103)
      I_R5     = STOF(ISTOF + 105)
      RT_37    = STOF(ISTOF + 107)
      I_R3     = STOF(ISTOF + 110)
      RT_40    = STOF(ISTOF + 111)
      RT_55    = STOF(ISTOF + 126)
      RT_57    = STOF(ISTOF + 129)
      RT_59    = STOF(ISTOF + 132)
      RT_61    = STOF(ISTOF + 135)
      RT_63    = STOF(ISTOF + 138)
      RT_65    = STOF(ISTOF + 141)
      RT_67    = STOF(ISTOF + 144)
      RT_69    = STOF(ISTOF + 147)
      RT_71    = STOF(ISTOF + 150)
      RT_73    = STOF(ISTOF + 153)
      RT_75    = STOF(ISTOF + 156)
      RT_77    = STOF(ISTOF + 159)
      RT_79    = STOF(ISTOF + 162)
      I_R1     = STOF(ISTOF + 164)
      RT_82    = STOF(ISTOF + 166)
      RT_85    = STOF(ISTOF + 169)
      RT_87    = STOF(ISTOF + 171)
      RT_88    = STOF(ISTOF + 172)
      RT_89    = STOF(ISTOF + 173)
      RT_90    = STOF(ISTOF + 180)
      RT_91    = STOF(ISTOF + 181)
      RT_92    = STOF(ISTOF + 182)
      EMOV_V   = STOF(ISTOF + 189)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Uacv_I(IT_0) = STOF(ISTOF + 4 + IT_0)
         Uacv_R(IT_0) = STOF(ISTOF + 9 + IT_0)
         Uac_I(IT_0) = STOF(ISTOF + 195 + IT_0)
         Uac_R(IT_0) = STOF(ISTOF + 198 + IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         RT_4(IT_0) = STOF(ISTOF + 18 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_6(IT_0) = STOF(ISTOF + 36 + IT_0)
         RT_7(IT_0) = STOF(ISTOF + 48 + IT_0)
         theta_I(IT_0) = STOF(ISTOF + 173 + IT_0)
         theta_R(IT_0) = STOF(ISTOF + 182 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)
      NT_6  = NODE(INODE + 6)
      NT_7  = NODE(INODE + 7)
      NT_8  = NODE(INODE + 8)
      NT_9  = NODE(INODE + 9)
      NT_10 = NODE(INODE + 10)
      NT_11 = NODE(INODE + 11)
      NT_12 = NODE(INODE + 12)
      NT_13 = NODE(INODE + 13)
      NT_14 = NODE(INODE + 14)
      NT_18 = NODE(INODE + 18)
      NT_23 = NODE(INODE + 31)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_15(IT_0) = NODE(INODE + 14 + IT_0)
         NT_21(IT_0) = NODE(INODE + 24 + IT_0)
         NT_22(IT_0) = NODE(INODE + 27 + IT_0)
         NT_24(IT_0) = NODE(INODE + 31 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[voltmeter] Voltmeter (Line - Line) 'U_R1'
      U_R1 = EMTDC_VVDC(SS(2), 0, NT_8)

! 20:[voltmeter] Voltmeter (Line - Line) 'U_R3'
      U_R3 = EMTDC_VVDC(SS(2), 0, NT_9)

! 30:[voltmeter] Voltmeter (Line - Line) 'U_R5'
      U_R5 = EMTDC_VVDC(SS(2), 0, NT_10)

! 40:[arrester] Arrester 
      EMOV_V = E_VZNO50(SS(1), (IBRCH(1)+29))
!

! 50:[voltmeter] Voltmeter (Line - Line) 'U_I2'
      U_I2 = EMTDC_VVDC(SS(1), 0, NT_5)

! 60:[voltmeter] Voltmeter (Line - Line) 'U_I6'
      U_I6 = EMTDC_VVDC(SS(1), 0, NT_6)

! 70:[ammeter] Current Meter 'I_R1'
      I_R1 = ( CBR((IBRCH(2)+8), SS(2)))

! 80:[voltmeter] Voltmeter (Line - Line) 'U_I4'
      U_I4 = EMTDC_VVDC(SS(1), 0, NT_7)

! 90:[ammeter] Current Meter 'I_R3'
      I_R3 = ( CBR((IBRCH(2)+9), SS(2)))

! 100:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Uac_R(1) = EMTDC_VVDC(SS(2), NT_15(1), 0)
      Uac_R(2) = EMTDC_VVDC(SS(2), NT_15(2), 0)
      Uac_R(3) = EMTDC_VVDC(SS(2), NT_15(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(2), (IBRCH(2)+5), (IBRCH(2)+6), (&
     &IBRCH(2)+7),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG2(ICALL_NO,1431929154,RVD1_1,"Pd")
      Pac_R = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(2), (IBRCH(2)+5), (IBRCH(2)+6), (&
     &IBRCH(2)+7),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG2(ICALL_NO,1431929154,RVD1_1,"Qd")
      Qac_R = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1431929154,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1431929154,1,"hide2")
      ENDIF

! 110:[ammeter] Current Meter 'I_R5'
      I_R5 = ( CBR((IBRCH(2)+10), SS(2)))

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Uacv_R(1) = EMTDC_VVDC(SS(2), NT_22(1), 0)
      Uacv_R(2) = EMTDC_VVDC(SS(2), NT_22(2), 0)
      Uacv_R(3) = EMTDC_VVDC(SS(2), NT_22(3), 0)

! 130:[ammeter] Current Meter 'I_I2'
      I_I2 = ( CBR((IBRCH(1)+9), SS(1)))

! 140:[ammeter] Current Meter 'I_I6'
      I_I6 = ( CBR((IBRCH(1)+10), SS(1)))

! 150:[voltmeter] Voltmeter (Line - Line) 'Udc_R'
      Udc_R = EMTDC_VVDC(SS(2), 0, NT_23)

! 160:[ammeter] Current Meter 'I_I4'
      I_I4 = ( CBR((IBRCH(1)+11), SS(1)))

! 170:[voltmeter] Voltmeter (Line - Line) 'Udc_I'
      Udc_I = EMTDC_VVDC(SS(1), 0, NT_18)

! 180:[ammeter] Current Meter 'I_R4'
      I_R4 = ( CBR((IBRCH(2)+11), SS(2)))

! 190:[ammeter] Current Meter 'I_R6'
      I_R6 = ( CBR((IBRCH(2)+12), SS(2)))

! 200:[ammeter] Current Meter 'I_R2'
      I_R2 = ( CBR((IBRCH(2)+13), SS(2)))

! 210:[voltmeter] Voltmeter (Line - Line) 'U_R4'
      U_R4 = EMTDC_VVDC(SS(2), NT_11, NT_12)

! 220:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Uacv_I(1) = EMTDC_VVDC(SS(1), NT_24(1), 0)
      Uacv_I(2) = EMTDC_VVDC(SS(1), NT_24(2), 0)
      Uacv_I(3) = EMTDC_VVDC(SS(1), NT_24(3), 0)

! 230:[ammeter] Current Meter 'I_I5'
      I_I5 = ( CBR((IBRCH(1)+12), SS(1)))

! 240:[voltmeter] Voltmeter (Line - Line) 'U_R6'
      U_R6 = EMTDC_VVDC(SS(2), NT_13, NT_12)

! 250:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Uac_I(1) = EMTDC_VVDC(SS(1), NT_21(1), 0)
      Uac_I(2) = EMTDC_VVDC(SS(1), NT_21(2), 0)
      Uac_I(3) = EMTDC_VVDC(SS(1), NT_21(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+6), (IBRCH(1)+7), (&
     &IBRCH(1)+8),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG2(ICALL_NO,1131790846,RVD1_1,"Pd")
      Pac_I = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+6), (IBRCH(1)+7), (&
     &IBRCH(1)+8),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG2(ICALL_NO,1131790846,RVD1_1,"Qd")
      Qac_I = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1131790846,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1131790846,1,"hide2")
      ENDIF

! 260:[ammeter] Current Meter 'I_I3'
      I_I3 = ( CBR((IBRCH(1)+13), SS(1)))

! 270:[voltmeter] Voltmeter (Line - Line) 'U_R2'
      U_R2 = EMTDC_VVDC(SS(2), NT_14, NT_12)

! 280:[ammeter] Current Meter 'I_I1'
      I_I1 = ( CBR((IBRCH(1)+14), SS(1)))

! 290:[voltmeter] Voltmeter (Line - Line) 'U_I5'
      U_I5 = EMTDC_VVDC(SS(1), NT_4, NT_1)

! 300:[voltmeter] Voltmeter (Line - Line) 'U_I3'
      U_I3 = EMTDC_VVDC(SS(1), NT_3, NT_1)

! 310:[voltmeter] Voltmeter (Line - Line) 'U_I1'
      U_I1 = EMTDC_VVDC(SS(1), NT_2, NT_1)

! 320:[ammeter] Current Meter 'Idc_R'
      Idc_R = (-CBR((IBRCH(2)+4), SS(2)))

! 330:[ammeter] Current Meter 'Idc_I'
      Idc_I = ( CBR((IBRCH(1)+1), SS(1)))

! 340:[pgb] Output Channel 'Uac_R'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = Uac_R(IVD1_1)
      ENDDO

! 350:[pgb] Output Channel 'Pac_R'

      PGB(IPGB+4) = Pac_R

! 360:[pgb] Output Channel 'Uacv_R'

      DO IVD1_1 = 1, 3
         PGB(IPGB+5+IVD1_1-1) = Uacv_R(IVD1_1)
      ENDDO

! 370:[pgb] Output Channel 'Qac_R'

      PGB(IPGB+8) = Qac_R

! 380:[pgb] Output Channel 'Udc_R'

      PGB(IPGB+9) = Udc_R

! 390:[pgb] Output Channel 'Idc_R'

      PGB(IPGB+10) = Idc_R

! 400:[pgb] Output Channel 'Uac_I'

      DO IVD1_1 = 1, 3
         PGB(IPGB+11+IVD1_1-1) = Uac_I(IVD1_1)
      ENDDO

! 410:[pgb] Output Channel 'Pac_I'

      PGB(IPGB+14) = Pac_I

! 420:[pgb] Output Channel 'Uacv_I'

      DO IVD1_1 = 1, 3
         PGB(IPGB+15+IVD1_1-1) = Uacv_I(IVD1_1)
      ENDDO

! 430:[pgb] Output Channel 'Qac_I'

      PGB(IPGB+18) = Qac_I

! 440:[datamerge] Merges data signals into an array 
      RT_4(1) = U_R1
      RT_4(2) = U_R2
      RT_4(3) = U_R3
      RT_4(4) = U_R4
      RT_4(5) = U_R5
      RT_4(6) = U_R6

! 450:[pgb] Output Channel 'Udc_I'

      PGB(IPGB+19) = Udc_I

! 460:[datamerge] Merges data signals into an array 
      RT_5(1) = I_R1
      RT_5(2) = I_R2
      RT_5(3) = I_R3
      RT_5(4) = I_R4
      RT_5(5) = I_R5
      RT_5(6) = I_R6

! 470:[pgb] Output Channel 'Idc_I'

      PGB(IPGB+20) = Idc_I

! 480:[pgb] Output Channel 'UV_R'

      DO IVD1_1 = 1, 6
         PGB(IPGB+21+IVD1_1-1) = RT_4(IVD1_1)
      ENDDO

! 490:[pgb] Output Channel 'IV_R'

      DO IVD1_1 = 1, 6
         PGB(IPGB+27+IVD1_1-1) = RT_5(IVD1_1)
      ENDDO

! 500:[datamerge] Merges data signals into an array 
      RT_7(1) = U_I1
      RT_7(2) = U_I2
      RT_7(3) = U_I3
      RT_7(4) = U_I4
      RT_7(5) = U_I5
      RT_7(6) = U_I6

! 510:[datamerge] Merges data signals into an array 
      RT_6(1) = I_I1
      RT_6(2) = I_I2
      RT_6(3) = I_I3
      RT_6(4) = I_I4
      RT_6(5) = I_I5
      RT_6(6) = I_I6

! 520:[pgb] Output Channel 'UV_I'

      DO IVD1_1 = 1, 6
         PGB(IPGB+33+IVD1_1-1) = RT_7(IVD1_1)
      ENDDO

! 530:[pgb] Output Channel 'IV_I'

      DO IVD1_1 = 1, 6
         PGB(IPGB+39+IVD1_1-1) = RT_6(IVD1_1)
      ENDDO

! 540:[datatap] Scalar/Array Tap 
      RT_90 = Uac_R(1)

! 560:[datatap] Scalar/Array Tap 
      RT_91 = Uac_R(2)

! 600:[datatap] Scalar/Array Tap 
      RT_92 = Uac_R(3)

! 610:[const] Real Constant 

      RT_85 = 0.05

! 620:[datatap] Scalar/Array Tap 
      RT_87 = Uac_I(1)

! 640:[datatap] Scalar/Array Tap 
      RT_88 = Uac_I(2)

! 660:[datatap] Scalar/Array Tap 
      RT_89 = Uac_I(3)

! 690:[const] Real Constant 

      RT_82 = 0.05

! 730:[const] Real Constant 

      RT_79 = 0.004

! 750:[const] Real Constant 

      RT_34 = 0.004

! 770:[const] Real Constant 

      RT_26 = 0.004

! 790:[const] Real Constant 

      RT_17 = 0.004

! 810:[const] Real Constant 

      RT_40 = 0.004

! 830:[const] Real Constant 

      RT_31 = 0.004

! 850:[const] Real Constant 

      RT_23 = 0.004

! 870:[const] Real Constant 

      RT_14 = 0.004

! 890:[const] Real Constant 

      RT_37 = 0.004

! 910:[const] Real Constant 

      RT_28 = 0.004

! 920:[const] Real Constant 

      RT_20 = 0.004

! 930:[const] Real Constant 

      RT_11 = 0.004

! 940:[tvekta] Phase-Locked Loop 
      RVD1_1 = 30.0*PI_BY180
      CALL COMPONENT_ID(ICALL_NO,227950849)
      CALL TVEKA1_EXE(RT_90,RT_91,RT_92,10.0,50.0,RVD1_1,0.02,1.2,0.8,th&
     &eta_R(1),RVD1_3,RVD1_2)
      CALL TVPULN(1,theta_R)
!

! 960:[tvekta] Phase-Locked Loop 
      RVD1_1 = 30.0*PI_BY180
      CALL COMPONENT_ID(ICALL_NO,1196896480)
      CALL TVEKA1_EXE(RT_87,RT_88,RT_89,10.0,50.0,RVD1_1,0.02,1.2,0.8,th&
     &eta_I(1),RVD1_3,RVD1_2)
      CALL TVPULN(1,theta_I)
!

! 970:[datatap] Scalar/Array Tap 
      RT_77 = theta_R(1)

! 990:[datatap] Scalar/Array Tap 
      RT_75 = theta_R(2)

! 1000:[datatap] Scalar/Array Tap 
      RT_73 = theta_R(3)

! 1010:[datatap] Scalar/Array Tap 
      RT_71 = theta_R(4)

! 1020:[datatap] Scalar/Array Tap 
      RT_69 = theta_R(5)

! 1030:[datatap] Scalar/Array Tap 
      RT_67 = theta_R(6)

! 1040:[datatap] Scalar/Array Tap 
      RT_55 = theta_I(1)

! 1050:[datatap] Scalar/Array Tap 
      RT_57 = theta_I(2)

! 1060:[datatap] Scalar/Array Tap 
      RT_59 = theta_I(3)

! 1070:[datatap] Scalar/Array Tap 
      RT_61 = theta_I(4)

! 1080:[datatap] Scalar/Array Tap 
      RT_63 = theta_I(5)

! 1090:[datatap] Scalar/Array Tap 
      RT_65 = theta_I(6)

! 2270:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2280:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2290:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2300:[Valve_ETT]  
      CALL Valve_ETTOut()


! 2310:[Valve_ETT]  
      CALL Valve_ETTOut()


! 2320:[Valve_ETT]  
      CALL Valve_ETTOut()


! 2330:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2340:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2350:[Valve_LTT]  
      CALL Valve_LTTOut()


! 2360:[Valve_ETT]  
      CALL Valve_ETTOut()


! 2370:[Valve_ETT]  
      CALL Valve_ETTOut()


! 2390:[Valve_ETT]  
      CALL Valve_ETTOut()


! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

! 1:[arrester] Arrester 
!

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 8) = Udc_I
      STOF(ISTOF + 9) = Udc_R
      STOF(ISTOF + 25) = U_R1
      STOF(ISTOF + 26) = U_R2
      STOF(ISTOF + 27) = U_R3
      STOF(ISTOF + 28) = U_R4
      STOF(ISTOF + 29) = U_R5
      STOF(ISTOF + 30) = U_R6
      STOF(ISTOF + 43) = U_I1
      STOF(ISTOF + 44) = U_I2
      STOF(ISTOF + 45) = U_I3
      STOF(ISTOF + 46) = U_I4
      STOF(ISTOF + 47) = U_I5
      STOF(ISTOF + 48) = U_I6
      STOF(ISTOF + 61) = Pac_R
      STOF(ISTOF + 62) = Qac_R
      STOF(ISTOF + 63) = Idc_R
      STOF(ISTOF + 64) = Idc_I
      STOF(ISTOF + 65) = Qac_I
      STOF(ISTOF + 66) = Pac_I
      STOF(ISTOF + 69) = RT_11
      STOF(ISTOF + 70) = I_I6
      STOF(ISTOF + 74) = RT_14
      STOF(ISTOF + 75) = I_I4
      STOF(ISTOF + 78) = RT_17
      STOF(ISTOF + 79) = I_I2
      STOF(ISTOF + 82) = RT_20
      STOF(ISTOF + 83) = I_I5
      STOF(ISTOF + 86) = RT_23
      STOF(ISTOF + 87) = I_I3
      STOF(ISTOF + 90) = RT_26
      STOF(ISTOF + 91) = I_I1
      STOF(ISTOF + 92) = I_R6
      STOF(ISTOF + 95) = RT_28
      STOF(ISTOF + 97) = I_R4
      STOF(ISTOF + 99) = RT_31
      STOF(ISTOF + 101) = I_R2
      STOF(ISTOF + 103) = RT_34
      STOF(ISTOF + 105) = I_R5
      STOF(ISTOF + 107) = RT_37
      STOF(ISTOF + 110) = I_R3
      STOF(ISTOF + 111) = RT_40
      STOF(ISTOF + 126) = RT_55
      STOF(ISTOF + 129) = RT_57
      STOF(ISTOF + 132) = RT_59
      STOF(ISTOF + 135) = RT_61
      STOF(ISTOF + 138) = RT_63
      STOF(ISTOF + 141) = RT_65
      STOF(ISTOF + 144) = RT_67
      STOF(ISTOF + 147) = RT_69
      STOF(ISTOF + 150) = RT_71
      STOF(ISTOF + 153) = RT_73
      STOF(ISTOF + 156) = RT_75
      STOF(ISTOF + 159) = RT_77
      STOF(ISTOF + 162) = RT_79
      STOF(ISTOF + 164) = I_R1
      STOF(ISTOF + 166) = RT_82
      STOF(ISTOF + 169) = RT_85
      STOF(ISTOF + 171) = RT_87
      STOF(ISTOF + 172) = RT_88
      STOF(ISTOF + 173) = RT_89
      STOF(ISTOF + 180) = RT_90
      STOF(ISTOF + 181) = RT_91
      STOF(ISTOF + 182) = RT_92
      STOF(ISTOF + 189) = EMOV_V

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 4 + IT_0) = Uacv_I(IT_0)
         STOF(ISTOF + 9 + IT_0) = Uacv_R(IT_0)
         STOF(ISTOF + 195 + IT_0) = Uac_I(IT_0)
         STOF(ISTOF + 198 + IT_0) = Uac_R(IT_0)
      END DO

! Array (1:6) quantities...
      DO IT_0 = 1,6
         STOF(ISTOF + 18 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 30 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 36 + IT_0) = RT_6(IT_0)
         STOF(ISTOF + 48 + IT_0) = RT_7(IT_0)
         STOF(ISTOF + 173 + IT_0) = theta_I(IT_0)
         STOF(ISTOF + 182 + IT_0) = theta_R(IT_0)
      END DO


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    Valve_LTTDyn_Begin  ! 
!     SUBR    Valve_ETTDyn_Begin  ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_11, RT_14, RT_17, RT_20, RT_23
      REAL     RT_26, RT_28, RT_31, RT_34, RT_37
      REAL     RT_40, RT_79, RT_82, RT_85

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD100_1(100), RVD100_2(100)
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER ISUBS, SS(2), IBRCH(2), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 6
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 2

      DO IT_0 = 1,2
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 32

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 32
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 40:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1952974997)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+29),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 550:[var_switch] Two State Switch 'DBlock_R'

! 570:[time-sig] Output of Simulation Time 

! 580:[var] Variable Input Slider 'Alpha_R'

! 590:[var] Variable Input Slider 'Maxcut_R'

! 610:[const] Real Constant 
      RT_85 = 0.05

! 630:[var_switch] Two State Switch 'DBlock_I'

! 650:[time-sig] Output of Simulation Time 

! 670:[var] Variable Input Slider 'Alpha_I'

! 680:[var] Variable Input Slider 'Maxcut_I'

! 690:[const] Real Constant 
      RT_82 = 0.05

! 700:[compar] Two Input Comparator 

! 710:[compar] Two Input Comparator 

! 720:[compar] Two Input Comparator 

! 730:[const] Real Constant 
      RT_79 = 0.004

! 740:[compar] Two Input Comparator 

! 750:[const] Real Constant 
      RT_34 = 0.004

! 760:[compar] Two Input Comparator 

! 770:[const] Real Constant 
      RT_26 = 0.004

! 780:[compar] Two Input Comparator 

! 790:[const] Real Constant 
      RT_17 = 0.004

! 800:[compar] Two Input Comparator 

! 810:[const] Real Constant 
      RT_40 = 0.004

! 820:[compar] Two Input Comparator 

! 830:[const] Real Constant 
      RT_31 = 0.004

! 840:[compar] Two Input Comparator 

! 850:[const] Real Constant 
      RT_23 = 0.004

! 860:[compar] Two Input Comparator 

! 870:[const] Real Constant 
      RT_14 = 0.004

! 880:[compar] Two Input Comparator 

! 890:[const] Real Constant 
      RT_37 = 0.004

! 900:[compar] Two Input Comparator 

! 910:[const] Real Constant 
      RT_28 = 0.004

! 920:[const] Real Constant 
      RT_20 = 0.004

! 930:[const] Real Constant 
      RT_11 = 0.004

! 950:[compar] Two Input Comparator 

! 980:[compar] Two Input Comparator 

! 1100:[compar] Two Input Comparator 

! 1110:[compar] Two Input Comparator 

! 1120:[compar] Two Input Comparator 

! 1130:[compar] Two Input Comparator 

! 1140:[compar] Two Input Comparator 

! 1150:[compar] Two Input Comparator 

! 1160:[compar] Two Input Comparator 

! 1170:[compar] Two Input Comparator 

! 1180:[compar] Two Input Comparator 

! 1190:[compar] Two Input Comparator 

! 1200:[compar] Two Input Comparator 

! 1210:[compar] Two Input Comparator 

! 1230:[inv] Interpolated Logic Inverter 

! 1250:[inv] Interpolated Logic Inverter 

! 1260:[fp_int] Interpolated Firing Pulses 

! 1270:[fp_int] Interpolated Firing Pulses 

! 1280:[fp_int] Interpolated Firing Pulses 

! 1290:[fp_int] Interpolated Firing Pulses 

! 1300:[datatap] Scalar/Array Tap 

! 1310:[fp_int] Interpolated Firing Pulses 

! 1320:[datatap] Scalar/Array Tap 

! 1330:[fp_int] Interpolated Firing Pulses 

! 1340:[datatap] Scalar/Array Tap 

! 1350:[unity] Type conversion block 

! 1360:[datatap] Scalar/Array Tap 

! 1370:[unity] Type conversion block 

! 1380:[datatap] Scalar/Array Tap 

! 1390:[unity] Type conversion block 

! 1410:[datatap] Scalar/Array Tap 

! 1420:[unity] Type conversion block 

! 1430:[fp_int] Interpolated Firing Pulses 

! 1450:[unity] Type conversion block 

! 1460:[fp_int] Interpolated Firing Pulses 

! 1480:[fp_int] Interpolated Firing Pulses 

! 1490:[unity] Type conversion block 

! 1510:[fp_int] Interpolated Firing Pulses 

! 1530:[datatap] Scalar/Array Tap 

! 1540:[fp_int] Interpolated Firing Pulses 

! 1560:[datatap] Scalar/Array Tap 

! 1570:[fp_int] Interpolated Firing Pulses 

! 1580:[datatap] Scalar/Array Tap 

! 1590:[unity] Type conversion block 

! 1600:[datatap] Scalar/Array Tap 

! 1610:[unity] Type conversion block 

! 1620:[datatap] Scalar/Array Tap 

! 1630:[unity] Type conversion block 

! 1650:[datatap] Scalar/Array Tap 

! 1660:[unity] Type conversion block 

! 1680:[unity] Type conversion block 

! 1700:[unity] Type conversion block 

! 1740:[delay] Binary ON Delay with Interpolation 

! 1750:[delay] Binary ON Delay with Interpolation 

! 1760:[delay] Binary ON Delay with Interpolation 

! 1770:[delay] Binary ON Delay with Interpolation 

! 1780:[delay] Binary ON Delay with Interpolation 

! 1790:[delay] Binary ON Delay with Interpolation 

! 1800:[delay] Binary ON Delay with Interpolation 

! 1810:[delay] Binary ON Delay with Interpolation 

! 1840:[Pulse2Level]  

! 1870:[Pulse2Level]  

! 1880:[delay] Binary ON Delay with Interpolation 

! 1890:[delay] Binary ON Delay with Interpolation 

! 1920:[Pulse2Level]  

! 1950:[Pulse2Level]  

! 1960:[delay] Binary ON Delay with Interpolation 

! 1970:[delay] Binary ON Delay with Interpolation 

! 2000:[Pulse2Level]  

! 2030:[Pulse2Level]  

! 2040:[datamerge] Merges data signals into an array 

! 2050:[datamerge] Merges data signals into an array 

! 2060:[datamerge] Merges data signals into an array 

! 2090:[Pulse2Level]  

! 2120:[Pulse2Level]  

! 2150:[Pulse2Level]  

! 2180:[Pulse2Level]  

! 2210:[Pulse2Level]  

! 2240:[Pulse2Level]  

! 2250:[pgb] Output Channel 'FP_I'

! 2260:[pgb] Output Channel 'FP_R'

! 2270:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2280:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2290:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2300:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2310:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2320:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2330:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2340:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2350:[Valve_LTT]  
      CALL Valve_LTTDyn_Begin()


! 2360:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2370:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2380:[pgb] Output Channel 'EMOV_V'

! 2390:[Valve_ETT]  
      CALL Valve_ETTDyn_Begin()


! 2400:[pgb] Output Channel 'FP_R_gct'

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1306313763)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+29),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1128012386)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+28),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,431349669)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+27),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1050192662)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+28),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1731079995)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+27),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      RTCF(NRTCF)   = 345.0*SQRT_2*SQRT_1BY3
      RTCF(NRTCF+1) = 50.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,1452455839)
      RVD1_1 = ONE_3RD*215.4
      RVD1_2 = 345.0*SQRT_1BY3
      RVD1_3 = 50.8*SQRT_1BY3
      CALL E_TF2W_CFG((IXFMR + 1),0,RVD1_1,50.0,0.1597,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      CALL E_TF2W_CFG((IXFMR + 2),0,RVD1_1,50.0,0.1597,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      CALL E_TF2W_CFG((IXFMR + 3),0,RVD1_1,50.0,0.1597,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      IF (0.0005 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0005
        RVD1_4 = 6.0/(215.4*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH(2)+14),SS(2),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(2)+15),SS(2),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(2)+16),SS(2),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(2)+17),SS(2),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(2)+18),SS(2),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(2)+19),SS(2),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2, (IBRCH(2)+20), (IBRCH(2)+21), (IBRCH(2)+22), (IB&
     &RCH(2)+23), (IBRCH(2)+24), (IBRCH(2)+25),0,0,0,0,0,0,SS(2),RVD1_1,&
     &0.2,1.17,50.0,0.0,1.0,0.0,0.1597,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD1_3&
     &,0.0,0.0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_BRANCH_CFG( (IBRCH(2)+26),SS(2),1,0,0,1.0,0.0,0.0)
      CALL E_1PVSRC_CFG(0,0,1,57.0,60.0,0.0,1.0,0.0,0.0,0.0,0.0,0.05)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_BRANCH_CFG( (IBRCH(1)+2),SS(1),1,0,0,1.0,0.0,0.0)
      CALL E_1PVSRC_CFG(0,0,1,10.0,60.0,0.0,1.0,0.0,0.0,0.0,0.0,0.05)

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,726492082)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+32),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,983826045)
      RVD1_1 = ONE_3RD*215.4
      RVD1_2 = 230.0*SQRT_1BY3
      RVD1_3 = 50.8*SQRT_1BY3
      CALL E_TF2W_CFG((IXFMR + 4),0,RVD1_1,50.0,0.1571,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      CALL E_TF2W_CFG((IXFMR + 5),0,RVD1_1,50.0,0.1571,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      CALL E_TF2W_CFG((IXFMR + 6),0,RVD1_1,50.0,0.1571,0.0023,RVD1_2,RVD&
     &1_3,1.0)
      IF (0.0005 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.0005
        RVD1_4 = 6.0/(215.4*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH(1)+15),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+16),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+17),SS(1),IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+18),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+19),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+20),SS(1),IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2, (IBRCH(1)+21), (IBRCH(1)+22), (IBRCH(1)+23), (IB&
     &RCH(1)+24), (IBRCH(1)+25), (IBRCH(1)+26),0,0,0,0,0,0,SS(1),RVD1_1,&
     &0.2,1.17,50.0,0.0,1.0,0.0,0.1571,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD1_3&
     &,0.0,0.0)

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,116628703)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+31),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      RTCF(NRTCF)   = 230.0*SQRT_2*SQRT_1BY3
      RTCF(NRTCF+1) = 50.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1867419198)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(2), (IBRCH(2)+30),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,1369814601)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+32),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,845949602)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+31),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

! 1:[arrester] Arrester 
      CALL COMPONENT_ID(ICALL_NO,6965202)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.2
      RVD100_2(2)  = 1.18
      RVD100_1(3)  = 1.0
      RVD100_2(3)  = 1.255
      RVD100_1(4)  = 4.00001
      RVD100_2(4)  = 1.353001
      RVD100_1(5)  = 4.00002
      RVD100_2(5)  = 1.353002
      RVD100_1(6)  = 4.00003
      RVD100_2(6)  = 1.353003
      RVD100_1(7)  = 4.00004
      RVD100_2(7)  = 1.353004
      RVD100_1(8)  = 4.00005
      RVD100_2(8)  = 1.353005
      RVD100_1(9)  = 4.00006
      RVD100_2(9)  = 1.353006
      RVD100_1(10) = 4.00007
      RVD100_2(10) = 1.353007
      RVD100_1(11) = 4.00008
      RVD100_2(11) = 1.353008
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+30),1,98.0,1.0,RVD100_1,RVD1&
     &00_2,"../datafile")

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    Valve_LTTOut_Begin  ! 
!     SUBR    Valve_ETTOut_Begin  ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_3, NT_4, NT_5, NT_6
      INTEGER  NT_7, NT_8, NT_9, NT_10, NT_11
      INTEGER  NT_12, NT_13, NT_14, NT_15(3)
      INTEGER  NT_18, NT_21(3), NT_22(3), NT_23
      INTEGER  NT_24(3)

! Control Signals
      REAL     RT_11, RT_14, RT_17, RT_20, RT_23
      REAL     RT_26, RT_28, RT_31, RT_34, RT_37
      REAL     RT_40, RT_79, RT_82, RT_85

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(2), IBRCH(2), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 38
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 2

      DO IT_0 = 1,2
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 32

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 32
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)
      NT_6  = NODE(INODE + 6)
      NT_7  = NODE(INODE + 7)
      NT_8  = NODE(INODE + 8)
      NT_9  = NODE(INODE + 9)
      NT_10 = NODE(INODE + 10)
      NT_11 = NODE(INODE + 11)
      NT_12 = NODE(INODE + 12)
      NT_13 = NODE(INODE + 13)
      NT_14 = NODE(INODE + 14)
      NT_18 = NODE(INODE + 18)
      NT_23 = NODE(INODE + 31)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_15(IT_0) = NODE(INODE + 14 + IT_0)
         NT_21(IT_0) = NODE(INODE + 24 + IT_0)
         NT_22(IT_0) = NODE(INODE + 27 + IT_0)
         NT_24(IT_0) = NODE(INODE + 31 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 100:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5

! 220:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5

! 250:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 340:[pgb] Output Channel 'Uac_R'

! 350:[pgb] Output Channel 'Pac_R'

! 360:[pgb] Output Channel 'Uacv_R'

! 370:[pgb] Output Channel 'Qac_R'

! 380:[pgb] Output Channel 'Udc_R'

! 390:[pgb] Output Channel 'Idc_R'

! 400:[pgb] Output Channel 'Uac_I'

! 410:[pgb] Output Channel 'Pac_I'

! 420:[pgb] Output Channel 'Uacv_I'

! 430:[pgb] Output Channel 'Qac_I'

! 440:[datamerge] Merges data signals into an array 

! 450:[pgb] Output Channel 'Udc_I'

! 460:[datamerge] Merges data signals into an array 

! 470:[pgb] Output Channel 'Idc_I'

! 480:[pgb] Output Channel 'UV_R'

! 490:[pgb] Output Channel 'IV_R'

! 500:[datamerge] Merges data signals into an array 

! 510:[datamerge] Merges data signals into an array 

! 520:[pgb] Output Channel 'UV_I'

! 530:[pgb] Output Channel 'IV_I'

! 540:[datatap] Scalar/Array Tap 

! 560:[datatap] Scalar/Array Tap 

! 600:[datatap] Scalar/Array Tap 

! 610:[const] Real Constant 
      RT_85 = 0.05

! 620:[datatap] Scalar/Array Tap 

! 640:[datatap] Scalar/Array Tap 

! 660:[datatap] Scalar/Array Tap 

! 690:[const] Real Constant 
      RT_82 = 0.05

! 730:[const] Real Constant 
      RT_79 = 0.004

! 750:[const] Real Constant 
      RT_34 = 0.004

! 770:[const] Real Constant 
      RT_26 = 0.004

! 790:[const] Real Constant 
      RT_17 = 0.004

! 810:[const] Real Constant 
      RT_40 = 0.004

! 830:[const] Real Constant 
      RT_31 = 0.004

! 850:[const] Real Constant 
      RT_23 = 0.004

! 870:[const] Real Constant 
      RT_14 = 0.004

! 890:[const] Real Constant 
      RT_37 = 0.004

! 910:[const] Real Constant 
      RT_28 = 0.004

! 920:[const] Real Constant 
      RT_20 = 0.004

! 930:[const] Real Constant 
      RT_11 = 0.004

! 940:[tvekta] Phase-Locked Loop 
      CALL TVEKA1_CFG(345000.0,50.0)

! 960:[tvekta] Phase-Locked Loop 
      CALL TVEKA1_CFG(530000.0,50.0)

! 970:[datatap] Scalar/Array Tap 

! 990:[datatap] Scalar/Array Tap 

! 1000:[datatap] Scalar/Array Tap 

! 1010:[datatap] Scalar/Array Tap 

! 1020:[datatap] Scalar/Array Tap 

! 1030:[datatap] Scalar/Array Tap 

! 1040:[datatap] Scalar/Array Tap 

! 1050:[datatap] Scalar/Array Tap 

! 1060:[datatap] Scalar/Array Tap 

! 1070:[datatap] Scalar/Array Tap 

! 1080:[datatap] Scalar/Array Tap 

! 1090:[datatap] Scalar/Array Tap 

! 2270:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2280:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2290:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2300:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


! 2310:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


! 2320:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


! 2330:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2340:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2350:[Valve_LTT]  
      CALL Valve_LTTOut_Begin()


! 2360:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


! 2370:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


! 2390:[Valve_ETT]  
      CALL Valve_ETTOut_Begin()


      RETURN
      END

