!=======================================================================
! Generated by  : PSCAD v4.6.2.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Valve_ETT
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Valve_ETTDyn(FP_GCT)

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    EMTDC_XTTRANS  ! 'Timed Transition'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: FP_GCT

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1

! Internal Variables
      REAL     RVD2_1(2), RVD2_2(2), Im, Lm, Re

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, IT_0                         ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 35
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 100
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      IT_1     = STOI(ISTOI + 2)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Valve_ETT.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[bin_delay] Timed ON/OFF Logic Transition 
!
      RVD2_1(1) = REAL(FP_GCT)
      RVD2_1(2) = 0.0
!
      CALL EMTDC_XTTRANS(0,0.0,5.0e-05,RVD2_1,RVD2_2)
!
      IT_1 = NINT(RVD2_2(1))

! 30:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1178237527)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+20), IT_1, 0.0)

! 40:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,636029053)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+38), IT_1, 0.0)

! 50:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,670229709)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+39), IT_1, 0.0)

! 60:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,747724825)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+6), IT_1, 0.0)

! 70:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1273705546)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+24), IT_1, 0.0)

! 80:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,278492781)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+42), IT_1, 0.0)

! 90:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,779970378)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+37), IT_1, 0.0)

! 100:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1922662588)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+11), IT_1, 0.0)

! 110:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,2102764080)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+29), IT_1, 0.0)

! 120:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1156985905)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+43), IT_1, 0.0)

! 130:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1396659965)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+34), IT_1, 0.0)

! 140:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,874022554)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+8), IT_1, 0.0)

! 150:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1628190942)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+26), IT_1, 0.0)

! 160:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1059087925)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+44), IT_1, 0.0)

! 170:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,770399032)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+36), IT_1, 0.0)

! 180:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,966782047)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+17), IT_1, 0.0)

! 190:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,954270720)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+35), IT_1, 0.0)

! 200:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,520121424)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+40), IT_1, 0.0)

! 210:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,632158492)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+31), IT_1, 0.0)

! 220:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,953778761)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+14), IT_1, 0.0)

! 230:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1502177627)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+32), IT_1, 0.0)

! 240:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,103170599)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+41), IT_1, 0.0)

! 250:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,1150239443)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+33), IT_1, 0.0)

! 260:[peswitch] Power electronic switch 
! Power Electronic Switch Model: GTO
      CALL COMPONENT_ID(ICALL_NO,775845046)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+2), IT_1, 0.0)

! 1:[Electrical_SaturableReactor]  


      Im = CBR( (IBRCH(1)+12),SS(1))
      IF (Im .lt. 0.0) THEN
        Im=-Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Lm = 0.0005248
      Else
        Lm = 0.0005248 * 0.08 / Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Re = 250.0
      Else
        Re = 250.0 * 0.08 / Im
      ENDIF

      CALL E_VARRLC1_EXE(1 ,SS(1) ,  (IBRCH(1)+12), 0, Lm , 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+10), 0, Re , 0.0)

! 1:[Electrical_SaturableReactor]  


      Im = CBR( (IBRCH(1)+9),SS(1))
      IF (Im .lt. 0.0) THEN
        Im=-Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Lm = 0.0005248
      Else
        Lm = 0.0005248 * 0.08 / Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Re = 250.0
      Else
        Re = 250.0 * 0.08 / Im
      ENDIF

      CALL E_VARRLC1_EXE(1 ,SS(1) ,  (IBRCH(1)+9), 0, Lm , 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+7), 0, Re , 0.0)

! 1:[Electrical_SaturableReactor]  


      Im = CBR( (IBRCH(1)+5),SS(1))
      IF (Im .lt. 0.0) THEN
        Im=-Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Lm = 0.0005248
      Else
        Lm = 0.0005248 * 0.08 / Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Re = 250.0
      Else
        Re = 250.0 * 0.08 / Im
      ENDIF

      CALL E_VARRLC1_EXE(1 ,SS(1) ,  (IBRCH(1)+5), 0, Lm , 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+4), 0, Re , 0.0)

! 1:[Electrical_SaturableReactor]  


      Im = CBR( (IBRCH(1)+3),SS(1))
      IF (Im .lt. 0.0) THEN
        Im=-Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Lm = 0.0005248
      Else
        Lm = 0.0005248 * 0.08 / Im
      ENDIF

      IF (Im .lt. 0.08) THEN
        Re = 250.0
      Else
        Re = 250.0 * 0.08 / Im
      ENDIF

      CALL E_VARRLC1_EXE(1 ,SS(1) ,  (IBRCH(1)+3), 0, Lm , 0.0)
      CALL E_VARRLC1_EXE(0 ,SS(1) ,  (IBRCH(1)+1), 0, Re , 0.0)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,376654772)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+30),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1877709825)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+22),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1034591416)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+21),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1902329860)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+13),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1090551387)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+28),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,16826424)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+23),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,159266144)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+19),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1703783335)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+15),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1821385585)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+27),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,1840868225)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+25),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,324448088)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+18),1)

! 1:[arrester] Arrester 'MOV_Valve'
!  Metal Oxide Gapless Surge Arrester: MOV_Valve
      CALL COMPONENT_ID(ICALL_NO,949059549)
      CALL ARRESTERZNO_EXE(SS(1), (IBRCH(1)+16),1)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOI(ISTOI + 1) = FP_GCT
      STOI(ISTOI + 2) = IT_1


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Valve_ETTOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    VBRANCH       ! Voltage across the branch
      REAL    E_VZNO50      ! Access calculated energy of arrester

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 35
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 100
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Valve_ETT.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

! 1:[arrester] Arrester 'MOV_Valve'
!

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------



!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Valve_ETTDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables
      REAL     RVD100_1(100), RVD100_2(100)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 35
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 100
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[bin_delay] Timed ON/OFF Logic Transition 

! 30:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 40:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 50:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 60:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 70:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 80:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 90:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 100:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 110:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 120:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 130:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 140:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 150:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 160:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 170:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 180:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 190:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 200:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 210:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 220:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 230:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 240:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 250:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 260:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(2, 0,0.000226, 161250.0, 8.0, 8.0, 0.0012, 0.0)

! 1:[Electrical_SaturableReactor]  
      CALL E_VARRLC1_CFG(1,SS(1), (IBRCH(1)+12),0)
      CALL E_VARRLC1_CFG(0,SS(1), (IBRCH(1)+10),0)

! 1:[Electrical_SaturableReactor]  
      CALL E_VARRLC1_CFG(1,SS(1), (IBRCH(1)+9),0)
      CALL E_VARRLC1_CFG(0,SS(1), (IBRCH(1)+7),0)

! 1:[Electrical_SaturableReactor]  
      CALL E_VARRLC1_CFG(1,SS(1), (IBRCH(1)+5),0)
      CALL E_VARRLC1_CFG(0,SS(1), (IBRCH(1)+4),0)

! 1:[Electrical_SaturableReactor]  
      CALL E_VARRLC1_CFG(1,SS(1), (IBRCH(1)+3),0)
      CALL E_VARRLC1_CFG(0,SS(1), (IBRCH(1)+1),0)

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,376654772)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+30),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1877709825)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+22),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1034591416)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+21),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1902329860)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+13),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1090551387)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+28),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,16826424)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+23),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,159266144)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+19),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1703783335)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+15),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1821385585)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+27),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,1840868225)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+25),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,324448088)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+18),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

! 1:[arrester] Arrester 'MOV_Valve'
      CALL COMPONENT_ID(ICALL_NO,949059549)
      RVD100_1 = 0.0
      RVD100_2 = 0.0
      RVD100_1(1)  = 1.0e-06
      RVD100_2(1)  = 1.0
      RVD100_1(2)  = 0.01
      RVD100_2(2)  = 1.1818
      RVD100_1(3)  = 0.1
      RVD100_2(3)  = 1.2386
      RVD100_1(4)  = 0.25
      RVD100_2(4)  = 1.2955
      RVD100_1(5)  = 0.5
      RVD100_2(5)  = 1.3295
      RVD100_1(6)  = 0.75
      RVD100_2(6)  = 1.3466
      RVD100_1(7)  = 1.0
      RVD100_2(7)  = 1.3636
      RVD100_1(8)  = 2.0
      RVD100_2(8)  = 1.4091
      RVD100_1(9)  = 2.5
      RVD100_2(9)  = 1.4261
      RVD100_1(10) = 3.0
      RVD100_2(10) = 1.4375
      RVD100_1(11) = 5.5
      RVD100_2(11) = 1.5
      CALL ARRESTERZNO_CFG(SS(1), (IBRCH(1)+16),1,8.8,2.0,RVD100_1,RVD10&
     &0_2,"../datafile")

      RETURN
      END

!=======================================================================

      SUBROUTINE Valve_ETTOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 35
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 100
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


      RETURN
      END

